FROM python:3.7-slim

# Copy local code to container image
ADD . /app
WORKDIR /app
COPY . .

# Install production depedencies
RUN pip install Flask 
RUN apt-get update
RUN pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
RUN pip install --upgrade google-cloud-pubsub

# Run API
ENTRYPOINT ["python"]
CMD ["app.py"]